# Numpy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# array creation with dtype  (1D array)
myarr = np.array([3,6,377,7],np.int32)

In [4]:
myarr

array([  3,   6, 377,   7])

In [5]:
myarr[0]

3

In [6]:
myarr[2]

377

In [7]:
myarr[1,4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [12]:
# 2D array
myarr2 = np.array([[3,6,377,7]],np.int32)

In [13]:
myarr2.dtype

dtype('int32')

In [14]:
myarr2[1,4] = 45

IndexError: index 1 is out of bounds for axis 0 with size 1

In [15]:
myarr2[0,3] = 45

In [16]:
myarr2

array([[  3,   6, 377,  45]])

In [17]:
myarr2[0,3]

45

In [20]:
myarr2[0,2] = 61

In [21]:
myarr2

array([[ 3,  6, 61, 45]])

 **Array Creation - Conversion from other python structures** (list,tuples) 

In [24]:
listarray = np.array([[1,2,3],[5,8,5,],[3,6,7]])

In [25]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [3, 6, 7]])

In [26]:
listarray.dtype

dtype('int32')

In [27]:
listarray.shape

(3, 3)

In [28]:
listarray.size

9

In [30]:
np.array({34,23,23})

array({34, 23}, dtype=object)

**Intrinsic numpy array creation objects - (arange,oneszeros,etc.)**

In [31]:
zeros = np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.shape

(2, 5)

In [34]:
zeros.dtype

dtype('float64')

In [36]:
rng = np.zeros((2,5))

In [37]:
rng

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
lspace = np.linspace(1,5,12)  # 5 will be size and 12 no.   ---- equally linear space elt.

In [41]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [43]:
emp = np.empty((4,6))  # random no.

In [44]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.95820760e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.78019761e-306, 1.37962185e-306,
        1.78019625e-306, 6.89812281e-307, 9.34609790e-307],
       [1.24610723e-306, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [47]:
emp_like = np.empty_like(lspace)  #copy the size of old array and create empty array

In [48]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [50]:
ide = np.identity(45)  #Identity matrix

In [51]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
ide.shape

(45, 45)

In [55]:
arr = np.arange(99)   # 0 to 99

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr = arr.reshape(3,33)

In [58]:
arr = arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

In [60]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [61]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [64]:
arr.shape

(3, 33)

**Numpy Axis**

In [68]:
arr1d = np.array([1,2,3,4,5])

In [69]:
arr1d.dtype 

dtype('int32')

In [71]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [75]:
arr2d.dtype

dtype('int32')

In [76]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
ar =  np.array(arr2d)

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
ar.sum(axis=0)  #Vertical

array([12, 15, 18])

In [82]:
ar.sum(axis=1)  #Horizontal

array([ 6, 15, 24])

In [83]:
ar.T  #Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
ar.flat

In [85]:
ar.flat
for item in ar.flat :    #  Value in row list
    print( item )

1
2
3
4
5
6
7
8
9


In [86]:
ar.ndim  # No of dimension

2

In [87]:
ar.size  # no of elts

9

In [88]:
ar.nbytes  # total bytes / memory

36

In [90]:
one = np.array([2,3,4,5,6,7])

In [91]:
one

array([2, 3, 4, 5, 6, 7])

In [92]:
one.argmax()  # Index where max value stayed

5

In [93]:
one.argmin()

0

In [94]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [101]:
one.sum()

27

In [95]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
ar.argmin()

0

In [97]:
ar.argmax()

8

In [98]:
ar.argmax(axis = 0)

array([2, 2, 2], dtype=int64)

In [99]:
ar.sum(axis = 0)

array([12, 15, 18])

In [100]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [102]:
ar.sum(index = 2)

TypeError: _sum() got an unexpected keyword argument 'index'

In [103]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [104]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [105]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [107]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [108]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [109]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [110]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [112]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])